server:
  port: 8000

#logging.level.com.smockin: ERROR

spring.main.allow-circular-references: true

smockin:
  auth.exclusions: '{"*.html":["GET"],"*.js":["GET"],"*.css":["GET"],"*.woff2":["GET"],"*.png":["GET"],"*.gif":["GET"],"*.ico":["GET"],"/auth":["POST"],"/user/mode":["GET"],"/mockedserver/rest/status":["GET"],"/mockedserver/jms/status":["GET"],"/mockedserver/ftp/status":["GET"],"/password/reset/token/*":["GET","POST"]}'

multi.user.mode: false

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20971520 #20 MB
      max-request-size: 20971520 #20 MB

---
# NOTE
# The 'start.sh' script overrides the below DB related params using values defined
# in the DB config file: '$USER_HOME/.smockin/db/db.properties'.
spring:
  profiles:
    active: production
  jpa:
    show-sql: false
    open-in-view: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${DB_URL:jdbc:h2:mem:smockin_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=PostgreSQL;}
    username: ${DB_USERNAME:smockin}
    password: ${DB_PASSWORD:smockin}
    hikari:
      poolName: smockinpool
      idle-timeout: 10000
      maximum-pool-size: 10
      minimum-idle: 10
  main:
    banner-mode: off
