server:
  port: 8000

smockin:
  auth.exclusions: '{"*.html":["GET"],"*.js":["GET"],"*.css":["GET"],"*.woff2":["GET"],"*.png":["GET"],"*.gif":["GET"],"*.ico":["GET"],"/auth":["POST"],"/user/mode":["GET"],"/mockedserver/rest/status":["GET"],"/mockedserver/jms/status":["GET"],"/mockedserver/ftp/status":["GET"],"/password/reset/token/*":["GET","POST"]}'

multi.user.mode: false

---
spring:
  profiles:
    active: production
  servlet:
    multipart:
      enabled: true
      max-file-size: 20971520 #20 MB
      max-request-size: 20971520 #20 MB
  jpa:
    show-sql: false
    open-in-view: false
  datasource:
    url: ${DB_URL:jdbc:h2:mem:smockin_db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;}
    username: ${DB_USERNAME:smockin}
    password: ${DB_PASSWORD:smockin}
    hikari:
      poolName: smockin-pool
      maximum-pool-size: 10
      minimum-idle: 10
  main:
    allow-circular-references: true
    banner-mode: off
