-- Remove generic sequence
DROP SEQUENCE IF EXISTS hibernate_sequence;

-- Sequence for every table
CREATE SEQUENCE app_config_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE rest_proj_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE server_config_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE smkn_user_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE mail_mock_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE mail_mock_msg_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE mail_mock_msg_atch_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE mail_mock_msg_atch_cont_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE proxy_forward_user_config_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE proxy_forward_mapping_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE rest_mock_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE rest_mock_def_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE rest_mock_js_handler_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE rest_mock_rule_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE rest_mock_rule_grp_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE rest_mock_rule_grp_cond_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE rest_mock_stateful_meta_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE s3_mock_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE s3_mock_dir_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE s3_mock_file_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE s3_mock_file_content_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE user_key_value_data_seq START WITH 1 INCREMENT BY 50;
